tasks:
  - name: pre_ready
    init: | 
      cargo build 
      rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
github:
  prebuilds:
    # enable for the default branch (defaults to true)
    master: true
vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - bungcip.better-toml
