tasks:
  - name: pre_ready
    init: |
      cargo build
    before: rustup component add rustfmt --toolchain nightly-x86_64-unknown-linux-gnu
github:
  prebuilds:
    master: true
vscode:
  extensions:
    - matklad.rust-analyzer
    - esbenp.prettier-vscode
    - serayuzgur.crates
    - vadimcn.vscode-lldb
    - bungcip.better-toml
